CREATE TABLE employees ( EmployeeID INT PRIMARY KEY Identity(1,1), 
FIRST_NAME varchar(20) not NULL, 
LAST_NAME varchar(25) NOT NULL, 
EMAIL varchar(25) NOT NULL, 
PHONE_NUMBER varchar(20) not NULL, 
HIRE_DATE date NOT NULL, 
JOB_ID int NOT NULL, 
SALARY decimal(8,2) not NULL,
COMMISSION_PER decimal(5,2) not NULL,
MANAGER_ID int not NULL, 
DEPARTMENT_ID int not null, 


CONSTRAINT FK_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID),
CONSTRAINT FK_JOB_ID FOREIGN KEY (JOB_ID) REFERENCES jobs(JOB_ID)
);

CREATE TABLE departments ( DEPARTMENT_ID INT PRIMARY KEY Identity(1,1));
