CREATE DATABASE Charity

USE Charity

CREATE TABLE Post 
	(PostId BIGINT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Post PRIMARY KEY, 
	UserId BIGINT NOT NULL,
	Description TEXT, 
	DonationTypeId BIGINT NOT NULL, 
	LocationName VARCHAR(50) NOT NULL, 
	City VARCHAR(30) NOT NULL, 
	State BIGINT NOT NULL, 
	Longitude DECIMAL(12,9) NOT NULL, 
	Latitude DECIMAL(12,9) NOT NULL, 
	PeopleCount INT NOT NULL, 
	TotalSpam INT NOT NULL,
	TotalUrgency INT NOT NULL,
	ImageURL NVARCHAR(MAX) NOT NULL, 
	CreatedBy VARCHAR(50) NOT NULL, 
	CreatedAt DATETIME NOT NULL, 
	UpdatedBy VARCHAR(50) NOT NULL, 
	UpdatedAt DATETIME NOT NULL, 
	Is_Published BIT NOT NULL,
	Close_At DATETIME NOT NULL, 
	Pincode INT NOT NULL
	)

ALTER TABLE Post WITH CHECK ADD CONSTRAINT FK_DonationType FOREIGN KEY(DonationTypeId) REFERENCES Donation(DonationTypeId)
ALTER TABLE Post WITH CHECK ADD CONSTRAINT FK_CityId FOREIGN KEY(CityId) REFERENCES City(CityId)
ALTER TABLE Post WITH CHECK ADD CONSTRAINT FK_StateId FOREIGN KEY(StateId) REFERENCES State(StateId)
ALTER TABLE Role WITH CHECK ADD CONSTRAINT FK_UserId FOREIGN KEY(UserId) REFERENCES Users(UserId)


CREATE TABLE Roles (
	Role_PermissionID BIGINT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Roles PRIMARY KEY,
	RoleType VARCHAR(50) NOT NULL,
	UserId BIGINT NOT NULL,
	ModuleId BIGINT NOT NULL,
	PermissionAdd BIT NOT NULL,
	PermissionEdit BIT NOT NULL,
	PermissionView BIT NOT NULL,
	PermissionDelete BIT NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL, 
	CreatedAt DATETIME NOT NULL, 
	UpdatedBy VARCHAR(50) NOT NULL, 
	UpdatedAt DATETIME NOT NULL 
	)

ALTER TABLE Roles WITH CHECK ADD CONSTRAINT FK_UserId FOREIGN KEY(UserId) REFERENCES Users(UserId)
ALTER TABLE Roles WITH CHECK ADD CONSTRAINT FK_Module FOREIGN KEY(Module) REFERENCES Module(ModuleId)

CREATE TABLE Users (
	UserId BIGINT NOT NULL CONSTRAINT PK_User PRIMARY KEY,
	UserType VARCHAR(10) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Area VARCHAR(50) NOT NULL,
	Occupation VARCHAR(30) NOT NULL,
	Gender VARCHAR(10) NOT NULL,
	ProfileImage NVARCHAR(MAX) NOT NULL,
	UserDescription VARCHAR(MAX) NOT NULL,
	UserName VARCHAR(20) NOT NULL,
	EmailAddress VARCHAR(30) NOT NULL,
	Verified_Email_Address BIT NOT NULL,
	PasswordHash NVARCHAR(MAX) NOT NULL,
	MobileNo VARCHAR(MAX) NOT NULL, 
	VerifiedMobNo BIT NOT NULL,
	AdditionalInfo TEXT NOT NULL,
	TotalPostCount BIGINT NOT NULL,
	DailyPostLimit BIT NOT NULL,
	LastPostedDate DATETIME NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL, 
	CreatedAt DATETIME NOT NULL, 
	UpdatedBy VARCHAR(50) NOT NULL, 
	UpdatedAt DATETIME NOT NULL,
	IsOrganisation BIT NOT NULL
	)


CREATE TABLE CharityEvent (
	EventId BIGINT NOT NULL CONSTRAINT PK_CharityEvent PRIMARY KEY,
	EventName VARCHAR(50) NOT NULL,
	EventDescription TEXT NOT NULL,
	EventOrganiserId BIGINT NOT NULL,
	EventDate DATETIME NOT NULL,
	EndDate DATETIME NOT NULL,
	StartTime TIME NOT NULL,
	EndTime TIME NOT NULL,
	IsPublished BIT NOT NULL,
	EventType VARCHAR(50) NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL, 
	CreatedAt DATETIME NOT NULL, 
	UpdatedBy VARCHAR(50) NOT NULL, 
	UpdatedAt DATETIME NOT NULL
	)

ALTER TABLE CharityEvent WITH CHECK ADD CONSTRAINT FK_UserId FOREIGN KEY(EventOrganiserId) REFERENCES Users(UserId)

CREATE TABLE Cities (
	CityId BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Cities PRIMARY KEY,
	StateId BIGINT NOT NULL,
	CityName VARCHAR(50) NOT NULL,
	IsPublished BIT NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL, 
	CreatedAt DATETIME NOT NULL, 
	UpdatedBy VARCHAR(50) NOT NULL, 
	UpdatedAt DATETIME NOT NULL
	)

ALTER TABLE Cities WITH CHECK ADD CONSTRAINT FK_Cities FOREIGN KEY(StateId) REFERENCES States(StateId)

CREATE TABLE States (
	StateId BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_States PRIMARY KEY,
	StateName VARCHAR(50) NOT NULL,
	IsPublished BIT NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL, 
	CreatedAt DATETIME NOT NULL, 
	UpdatedBy VARCHAR(50) NOT NULL, 
	UpdatedAt DATETIME NOT NULL
	)
CREATE TABLE Module (
    ModuleId BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Module PRIMARY KEY,
    ModuleName VARCHAR(30),
    ModuleType VARCHAR(20),
    IsPublished BIT NOT NULL,
    CreatedBy VARCHAR(50) NOT NULL, 
    CreatedAt DATETIME NOT NULL, 
    UpdatedBy VARCHAR(50) NOT NULL, 
    UpdatedAt DATETIME NOT NULL
    )

 

CREATE TABLE Organisation (
    OrganisationId BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Organisation PRIMARY KEY,
    OrganisationUserId BIGINT NOT NULL,
    OrganisationName VARCHAR(50),
    OrganisationAddress VARCHAR(MAX),
    OrganisationDescription TEXT NOT NULL,
    OrganisationContactNo NVARCHAR(50) NOT NULL,
    OrganisationLogoURL NVARCHAR(MAX) NOT NULL,
    AdditionalInfo TEXT,
    IsPublished BIT NOT NULL,
    CreatedBy VARCHAR(50) NOT NULL, 
    CreatedAt DATETIME NOT NULL, 
    UpdatedBy VARCHAR(50) NOT NULL, 
    UpdatedAt DATETIME NOT NULL
    )
ALTER TABLE Organisation WITH CHECK ADD CONSTRAINT FK_OrgUser FOREIGN KEY(OrganisationUserId) REFERENCES Users(UserId)

 

CREATE TABLE ContributionType (
    ContributionTypeId BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Contro PRIMARY KEY,
    ContributionTypeName VARCHAR(50) NOT NULL,
    IsPublished BIT NOT NULL,
    CreatedBy VARCHAR(50) NOT NULL, 
    CreatedAt DATETIME NOT NULL, 
    UpdatedBy VARCHAR(50) NOT NULL, 
    UpdatedAt DATETIME NOT NULL
    )

 

CREATE TABLE Volunteer (
    VolunteerId BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Volunteer PRIMARY KEY,
    VolunteerUserId BIGINT NOT NULL,
    IsPublished BIT NOT NULL,
    CreatedBy VARCHAR(50) NOT NULL, 
    CreatedAt DATETIME NOT NULL, 
    UpdatedBy VARCHAR(50) NOT NULL, 
    UpdatedAt DATETIME NOT NULL
    )
ALTER TABLE Volunteer WITH CHECK ADD CONSTRAINT FK_Volunteer FOREIGN KEY(VolunteerUserId) REFERENCES Users(UserId)

 

CREATE TABLE Place (
    PlaceID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Help PRIMARY KEY,
    Locations VARCHAR(50) NOT NULL,
    PeopleCount BIGINT NOT NULL,
    IsPublished BIT NOT NULL,
    CreatedBy VARCHAR(50) NOT NULL, 
    CreatedAt DATETIME NOT NULL, 
    UpdatedBy VARCHAR(50) NOT NULL, 
    UpdatedAt DATETIME NOT NULL
    )

 

CREATE TABLE Urgency (
    UrgencyId BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Urgent PRIMARY KEY,
    PostId BIGINT NOT NULL,
    UserId BIGINT NOT NULL,
    IsPublished BIT NOT NULL,
    CreatedBy VARCHAR(50) NOT NULL, 
    CreatedAt DATETIME NOT NULL, 
    UpdatedBy VARCHAR(50) NOT NULL, 
    UpdatedAt DATETIME NOT NULL
    )
ALTER TABLE Urgency WITH CHECK ADD CONSTRAINT FK_UrgentPost FOREIGN KEY(PostId) REFERENCES Post(PostId)
ALTER TABLE Urgency WITH CHECK ADD CONSTRAINT FK_UrgentUser FOREIGN KEY(UserId) REFERENCES Users(UserId)

 

CREATE TABLE Spam (
    SpamId BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Spam PRIMARY KEY,
    PostId BIGINT NOT NULL,
    UserId BIGINT NOT NULL,
    SpamLimit BIT NOT NULL,
    IsPublished BIT NOT NULL,
    CreatedBy VARCHAR(50) NOT NULL, 
    CreatedAt DATETIME NOT NULL, 
    UpdatedBy VARCHAR(50) NOT NULL, 
    UpdatedAt DATETIME NOT NULL
    ) 
ALTER TABLE Spam WITH CHECK ADD CONSTRAINT FK_SpamPost FOREIGN KEY(PostId) REFERENCES Post(PostId)
ALTER TABLE Spam WITH CHECK ADD CONSTRAINT FK_SpamUser FOREIGN KEY(UserId) REFERENCES Users(UserId)